version: '3.8'

services:
  backend:
    build: .
    container_name: scholarship_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scholarship_db
      - SECRET_KEY=supersecretjwtkeyforproductionchangeinenvfile
      - UPLOAD_DIR=app/uploads
      - ML_SERVICE_URL=http://127.0.0.1:8000/api/v1/ml/predict
    depends_on:
      - db
    volumes:
      - ./app/uploads:/app/app/uploads

  db:
    image: postgres:16-alpine
    container_name: scholarship_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scholarship_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
